---
defaults: &defaults
  compute:
    hourly: 0.1
  java:
    general:
      standard: 
        monthly: 450
        hourly: 0.75
      enterprise: 
        monthly: 1200
        hourly: 2.02
      suite: 
        monthly: 2800
        hourly: 4.7
    high:
      standard: 
        monthly: 550
        hourly: 0.924
      enterprise: 
        monthly: 1300
        hourly: 2.184
      suite: 
        monthly: 2900
        hourly: 4.872
  soa:
    full: 5500
    api: 3500
    mft: 4500
  database:
    general:
      standard: 
        monthly: 600
        hourly: 1.08
      enterprise: 
        monthly: 3000
        hourly: 5.04
      hp: 
        monthly: 4000
        hourly: 6.72
      xp:
        monthly: 5000
        hourly: 8.401
    high:
      standard: 
        monthly: 700
        hourly: 1.176
      enterprise: 
        monthly: 3100
        hourly: 5.208
      hp: 
        monthly: 4100
        hourly: 6.888
      xp:
        monthly: 5100
        hourly: 8.569

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults